### PR TITLE
[STC vote required] Process to approve x-SDK changes.

### PR DESCRIPTION
**Pull request by artursouza**

### CODE REVIEW

**Comment by yaron2** [comment]
+1 binding

**Comment by msfussell** [comment]
+1 binding

**Comment by cvictory** [comment]
+1 binding

**Comment by JoshVanL** [comment]
+1 non-binding

**Comment by paulyuk** [comment]
+1 binding

I do ask that SIG and maintainers are very mindful of costs and churn this results in as part of the decision process.

**Pull request merged**
